apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Explore star trends showing daily stars and go
      beyond the 40k-star limit.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/8088857?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://github.com/emanuelef/daily-stars-explorer/assets/48717/9402696a-0f23-445c-a4fe-29a10c18bc3e"]'
    kubero.dev/template.source: https://github.com/emanuelef/daily-stars-explorer
    kubero.dev/template.categories: '["developer-tools"]'
    kubero.dev/template.title: Stars Explorer
    kubero.dev/template.website: https://github.com/emanuelef/daily-stars-explorer
  labels:
    manager: kubero
  name: daily-stars-explorer
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: HOST
    value: 0.0.0.0
  - name: PAT
    value: CHANGE-ME
  - name: PAT2
    value: CHANGE-ME
  - name: REDDIT_CLIENT_ID
    value: CHANGE-ME
  - name: REDDIT_CLIENT_SECRET
    value: CHANGE-ME
  - name: REDDIT_USER_AGENT
    value: CHANGE-ME
  - name: REDDIT_USERNAME
    value: CHANGE-ME
  - name: REDDIT_PASSWORD
    value: CHANGE-ME
  - name: YOUTUBE_API_KEY
    value: CHANGE-ME
  extraVolumes: []
  image:
    containerPort: 8080
    pullPolicy: Always
    repository: ghcr.io/emanuelef/daily-stars-explorer
    tag: latest
  name: daily-stars-explorer
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
