apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Blazing fast file uploader and awesome bunker
      written in node!
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/115422728?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://user-images.githubusercontent.com/7425261/245041422-659068cd-f154-4fe0-860f-4478e0f859d5.png","https://user-images.githubusercontent.com/7425261/245041448-83dae9d1-5f71-404a-b79c-19fb4d0dfd62.png","https://user-images.githubusercontent.com/7425261/245041459-0dad05a8-f42b-4834-983f-2ca82eedb176.png"]'
    kubero.dev/template.source: https://github.com/chibisafe/chibisafe
    kubero.dev/template.categories: '[ "utilities", "work" ]'
    kubero.dev/template.title: Chibisafe
    kubero.dev/template.website: https://chibisafe.moe
  name: chibisafe
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: chibisafe
  envVars: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    mountPath: /home/node/chibisafe/database
    name: chibisafe-db-volume
    size: 1Gi
  - accessModes:
    - ReadWriteOnce
    mountPath: /home/node/chibisafe/uploads
    name: chibisafe-uploads-volume
    size: 1Gi
  - accessModes:
    - ReadWriteOnce
    mountPath: /home/node/chibisafe/logs
    name: chibisafe-logs-volume
    size: 1Gi
  image:
    containerPort: '8000'
    repository: chibisafe/chibisafe
    run:
      securityContext:
        readOnlyRootFilesystem: false
    tag: latest
  name: chibisafe
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
