apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Etherpad is a real-time collaborative editor
      scalable to thousands of simultaneous real time users.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/181731?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '["https://github.com/ether/etherpad-lite/blob/develop/doc/docker.md"]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/ether/etherpad-lite/develop/doc/images/etherpad_demo.gif"]'
    kubero.dev/template.source: https://github.com/ether/etherpad-lite
    kubero.dev/template.categories: '["collaboration","documents","editor","writing"]'
    kubero.dev/template.title: Etherpad
    kubero.dev/template.website: https://etherpad.org/
  name: etherpad
spec:
  addons:
  - displayName: Kubero Postgresql
    env: []
    icon: /img/addons/postgresql.png
    id: kubero-operator
    kind: KuberoPostgresql
    resourceDefinitions:
      KuberoPostgresql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoPostgresql
        metadata:
          name: etherpad-postgresql
        spec:
          postgresql:
            global:
              postgresql:
                auth:
                  database: postgresql
                  password: etherpad
                  postgresPassword: etherpad
                  username: etherpad
              storageClass: standard
            primary:
              persistence:
                size: 1Gi
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: DB_TYPE
    value: postgres
  - name: DB_PASS
    value: etherpad
  - name: DB_USER
    value: etherpad
  - name: DB_NAME
    value: postgresql
  - name: DB_HOST
    value: etherpad-postgresql
  - name: DB_PORT
    value: '5432'
  extraVolumes: []
  image:
    containerPort: '8080'
    repository: etherpad/etherpad
    run:
      securityContext:
        readOnlyRootFilesystem: false
    tag: latest
  name: etherpad
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
