apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Open source API development ecosystem
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/56705483?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/hoppscotch/hoppscotch/main/packages/hoppscotch-common/public/images/banner-light.png"]'
    kubero.dev/template.source: https://github.com/hoppscotch/hoppscotch
    kubero.dev/template.categories: '["development", "development"]'
    kubero.dev/template.title: Hoppscotch
    kubero.dev/template.website: https://hoppscotch.io
  name: hopscotch
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes: []
  image:
    containerPort: '3000'
    repository: hoppscotch/hoppscotch
    tag: latest
  name: hopscotch
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
