apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: vaultwarden
spec:
  name: vaultwarden
  deploymentstrategy: docker
  image:
    repository: vaultwarden/server
    tag: latest
    containerPort: "80"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /data
    name: vaultwarden-data
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0