apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: The open source Calendly alternative. You are
      in charge of your own data, workflow and appearance
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/79145102?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://user-images.githubusercontent.com/8019099/176390354-f1bc7069-0341-437a-9bb8-eb41092b4016.gif"]'
    kubero.dev/template.source: https://github.com/calcom/cal.com
    kubero.dev/template.categories: '["calendar"]'
    kubero.dev/template.title: cal.com
    kubero.dev/template.website: https://cal.com/
  name: calcom
spec:
  addons:
  - displayName: Kubero Postgresql
    env: []
    icon: /img/addons/postgresql.png
    id: kubero-operator
    kind: KuberoPostgresql
    resourceDefinitions:
      KuberoPostgresql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoPostgresql
        metadata:
          name: calcom-postgresql
        spec:
          postgresql:
            global:
              postgresql:
                auth:
                  database: postgresql
                  password: calcom
                  postgresPassword: calcom
                  username: calcom
              storageClass: standard
            primary:
              persistence:
                size: 1Gi
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: DATABASE_URL
    value: postgresql://calcom:calcom@calcom-postgresql/postgresql
  - name: NODE_ENV
    value: production
  - name: NEXT_PUBLIC_LICENSE_CONSENT
    value: agree
  - name: NEXTAUTH_SECRET
    value: palimpalim
  - name: CALENDSO_ENCRYPTION_KEY
    value: bumpulum
  extraVolumes: []
  image:
    containerPort: '3000'
    repository: calcom.docker.scarf.sh/calcom/cal.com
    run:
      securityContext:
        readOnlyRootFilesystem: false
    tag: latest
  name: calcom
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
