apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Kener is a Modern Self hosted Status Page
    kubero.dev/template.icon: https://kener.ing/logo.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://camo.githubusercontent.com/8d4f2ea8ac5a6200ad87e39a21be25c5b279d540a886db131a076ef69227ca7a/68747470733a2f2f6b656e65722e696e672f73732e706e67"]'
    kubero.dev/template.source: https://github.com/rajnandan1/kener
    kubero.dev/template.categories: '["monitoring"]'
    kubero.dev/template.title: Kener
    kubero.dev/template.website: https://www.kener.ing
  name: kener
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  extraVolumes:
    mountPath: /config
    name: kener-volume
    size: 1Gi
  image:
    containerPort: '3000'
    pullPolicy: Always
    repository: rajnandan1/kener
    tag: latest
  name: kener
  web:
    replicaCount: 1
