apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: statusnook
    annotations:
        icon: "www.svgrepo.com/show/310016/status.svg"
        description: 'StatusNook is a simple status page for your services.'
        source: "github.com/goksan/statusnook"
        website: "statusnook.com"
        documentation: ""
        screenshots: |
            - https://raw.githubusercontent.com/atuinsh/atuin/main/demo.gif
        tags: |
            - monitoring
        installation-message: |
            Admin account is created with the first website visit
    labels:
        manager: kubero
spec:
    name: statusnook
    deploymentstrategy: docker
    envVars: []
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /app/statusnook-data
          name: statusnook-volume
          size: 1Gi
          storageClass: standard
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "8000"
        pullPolicy: Always
        repository: goksan/statusnook
        tag: latest