apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: laravel
spec:
  name: laravel
  deploymentstrategy: git
  image:
    build:
      command: composer install; chown -R 1000:1000 /app; mkdir -p storage/framework/cache
        storage/framework/sessions storage/framework/views storage/framework/testing
        storage/logs storage/app/public
      repository: composer
      tag: latest
    run:
      command: apache2-foreground
      readOnlyAppStorage: false
      repository: ghcr.io/kubero-dev/buildpacks/php
      securityContext:
        readOnlyRootFilesystem: false
      tag: latest
    containerPort: "8080"
  addons: []
  envVars:
  - name: APP_NAME
    value: Demo
  - name: APP_KEY
    value: base64:YmhiZ3J6NXV4aGE1bnh6cTh0eXJ0NzFqanozMnRmOXk=
  - name: APP_ENV
    value: local
  - name: APP_DEBUG
    value: "false"
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /app/storage
    name: laravel-storage
    size: 1Gi
  web:
    replicaCount: 1
  worker:
    replicaCount: 0