apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Painless self-hosted all-in-one software development
      service, includes Git hosting, code review, team collaboration, package registry
      and CI/CD
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/12724356?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://camo.githubusercontent.com/134f49a62801ab393c211125515d108439c67b59befb2ec3e42e7235af4f5d6c/68747470733a2f2f646c2e67697465612e696f2f73637265656e73686f74732f686f6d655f74696d656c696e652e706e67","https://camo.githubusercontent.com/186c2a4c286dcb5e6c419ae11c062721ba73eafcc40e518f237adcc9985385db/68747470733a2f2f646c2e67697465612e696f2f73637265656e73686f74732f757365725f70726f66696c652e706e67"]'
    kubero.dev/template.source: https://github.com/go-gitea/gitea
    kubero.dev/template.categories: '["work","development","collaboration"]'
    kubero.dev/template.title: gitea
    kubero.dev/template.website: https://gitea.io/
  name: gitea
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /data
    name: gitea-data
    size: 10Gi
  image:
    containerPort: '3000'
    repository: gitea/gitea
    run:
      securityContext:
        readOnlyRootFilesystem: false
    tag: latest
  name: gitea
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
