apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: 'A lightning-fast search engine that fits effortlessly
      into your apps, websites, and workflow '
    kubero.dev/template.icon: https://www.meilisearch.com/apple-touch-icon.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://github.com/meilisearch/meilisearch/raw/main/assets/demo-light.gif"]'
    kubero.dev/template.source: https://github.com/meilisearch/meilisearch
    kubero.dev/template.categories: '["accessories", "development"]'
    kubero.dev/template.title: Meilisearch
    kubero.dev/template.website: https://www.meilisearch.com/
  name: meilisearch
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /meili_data
    name: meilidata-volume
    size: 1Gi
    storageClass: standard
  image:
    containerPort: '7700'
    repository: getmeili/meilisearch
    tag: latest
  name: meilisearch
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
