apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: meilisearch
spec:
  name: meilisearch
  deploymentstrategy: docker
  image:
    repository: getmeili/meilisearch
    tag: latest
    containerPort: "7700"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /meili_data
    name: meilidata-volume
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0