apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: A self-hosted, file based task management board
      that supports Markdown syntax.
    kubero.dev/template.icon: https://raw.githubusercontent.com/BaldissaraMatheus/Tasks.md/main/frontend/public/favicon/android-chrome-192x192.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/BaldissaraMatheus/Tasks.md/main/public/demonstration.gif"]'
    kubero.dev/template.source: https://github.com/BaldissaraMatheus/Tasks.md
    kubero.dev/template.categories: '["productivity", "utilities", "work"]'
    kubero.dev/template.title: Tasks.md
    kubero.dev/template.website: https://hub.docker.com/r/baldissaramatheus/tasks.md
  name: tasksmd
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: TITLE
    value: Demo
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    mountPath: /api/files/
    name: tasksmd-files
    size: 1Gi
  image:
    containerPort: '8080'
    repository: baldissaramatheus/tasks.md
    tag: latest
  name: tasksmd
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
