apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: rocketchat
spec:
  name: rocketchat
  deploymentstrategy: docker
  image:
    repository: registry.rocket.chat/rocketchat/rocket.chat
    tag: latest
    containerPort: "3000"
  addons:
  - displayName: Kubero MongoDB
    env: []
    icon: /img/addons/MongoDB.png
    id: kubero-operator
    kind: KuberoMongoDB
    resourceDefinitions:
      KuberoMongoDB:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMongoDB
        metadata:
          name: rocketchat-mongodb
        spec:
          mongodb:
            architecture: standalone
            auth:
              databases:
              - kubero
              passwords:
              - rocket
              rootPassword: mongoroot
              rootUser: root
              usernames:
              - rocket
            directoryPerDB: false
            disableJavascript: false
            global:
              storageClass: standard
            persistence:
              size: 1Gi
            replicaCount: 1
  envVars:
  - name: MONGO_URL
    value: mongodb://rocket:rocket@rocketchat-mongodb:27017/kubero
  - name: ROOT_URL
    value: https://rocketchat.demo.kubero.dev
  - name: DEPLOY_METHOD
    value: docker
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0