apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Dashy helps you organize your self-hosted services
      by making them accessible from a single place.
    kubero.dev/template.icon: https://i.ibb.co/yhbt6CY/dashy.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://i.ibb.co/L8YbNNc/dashy-demo2.gif"]'
    kubero.dev/template.source: https://github.com/Lissy93/dashy
    kubero.dev/template.categories: '["dashboard", "utility"]'
    kubero.dev/template.title: Dashy
    kubero.dev/template.website: https://dashy.to/
  name: dashy
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: NODE_ENV
    value: production
  extraVolumes: []
  image:
    containerPort: '8080'
    repository: lissy93/dashy
    tag: latest
  name: dashy
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
