apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: symfony
spec:
  name: symfony
  deploymentstrategy: git
  image:
    build:
      command: composer install; mkdir -p var/cache var/log; chown -R 1000:1000 /app
      repository: composer
      tag: latest
    run:
      command: apache2-foreground
      readOnlyAppStorage: false
      repository: ghcr.io/kubero-dev/buildpacks/php
      securityContext:
        readOnlyRootFilesystem: false
      tag: latest
    containerPort: "8080"
  addons: []
  envVars: 
  - name: APP_SECRET
    value: 20bd009a24d5db6d813bccb1a539da7a
  - name: APP_DEBUG
    value: "false"
  - name: APP_ENV
    value: prod
  - name: PHP_EXTENSION_INTL
    value: "1"
  cronjobs: []
  extraVolumes: 
  - mountPath: /app/var
    name: symfony-var
    size: 1Gi
  web:
    replicaCount: 1
  worker:
    replicaCount: 0