apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: traggo
spec:
  name: traggo
  deploymentstrategy: docker
  image:
    repository: traggo/server
    tag: latest
    containerPort: "3030"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /opt/traggo/data
    name: traggo-data
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0