apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Low code project to build admin panels, internal
      tools, and dashboards. Integrates with 15+ databases and any API.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/67620218?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://images.ctfassets.net/lpvian6u6i39/57xRxbPxLB5Rx6YYCQstyW/d605683e09640cabbb15e9a9d65dc03d/img-cta.png"]'
    kubero.dev/template.source: https://github.com/appsmithorg/appsmith
    kubero.dev/template.tags: '["admin-dashboard","workflows","app-builder"]'
    kubero.dev/template.title: Appsmith
    kubero.dev/template.website: https://www.appsmith.com
  name: appsmith
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /appsmith-stacks
    name: appsmith-volume
    size: 1Gi
    storageClass: standard
  image:
    containerPort: '80'
    repository: appsmith/appsmith-ce
    run:
      securityContext:
        readOnlyRootFilesystem: false
    tag: latest
  name: appsmith
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
