apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    description: Atuin replaces your existing shell history with a SQLite database,
      and records additional context for your commands.
    documentation: ''
    icon: avatars.githubusercontent.com/u/122059230?s=200&v=4
    installation-message: 'Make sure you have selected the correct storageclass for
      the database. If you are unsure, you can check the available storage classes
      by running the following command:
      ```bash
      kubectl get storageclass
      ```
      '
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Atuin replaces your existing shell history with
      a SQLite database, and records additional context for your commands.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/122059230?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/atuinsh/atuin/main/demo.gif"]'
    kubero.dev/template.source: https://github.com/atuinsh/atuin
    kubero.dev/template.tags: '["administration"]'
    kubero.dev/template.title: Atuin
    kubero.dev/template.website: https://atuin.sh/
    screenshots: '- https://raw.githubusercontent.com/atuinsh/atuin/main/demo.gif
      '
    source: github.com/atuinsh/atuin
    tags: '- administration
      '
    website: atuin.sh
  labels:
    manager: kubero
  name: atuin
spec:
  addons:
  - displayName: Postgresql
    env: []
    icon: /img/addons/pgsql.svg
    id: kubero-operator
    kind: KuberoPostgresql
    resourceDefinitions:
      KuberoPostgresql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoPostgresql
        metadata:
          name: atuin-autin-postgresql
        spec:
          postgresql:
            global:
              postgresql:
                auth:
                  database: atuin
                  password: atuin
                  postgresPassword: atuin
                  username: atuin
              storageClass: standard
            primary:
              persistence:
                size: 1Gi
    version:
      latest: 0.1.5
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: ATUIN_HOST
    value: 0.0.0.0
  - name: ATUIN_OPEN_REGISTRATION
    value: 'true'
  - name: ATUIN_DB_URI
    value: postgres://atuin:atuin@atuin-autin-postgresql/atuin
  - name: RUST_LOG
    value: info,atuin_server=debug
  extraVolumes: []
  image:
    command:
    - atuin
    - server
    - start
    containerPort: '8888'
    pullPolicy: Always
    repository: ghcr.io/atuinsh/atuin
    tag: latest
  name: atuin
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
