apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: The Registry is a stateless, highly scalable
      server side application that stores and lets you distribute Docker images.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/5429470?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: 'null'
    kubero.dev/template.source: https://github.com/distribution/distribution
    kubero.dev/template.tags: '["docker"]'
    kubero.dev/template.title: Docker Registry
    kubero.dev/template.website: https://docs.docker.com/registry/
  name: dockerregistry
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /var/lib/registry
    name: registry-data
    size: 10Gi
  image:
    containerPort: '5000'
    repository: registry
    run:
      securityContext:
        readOnlyRootFilesystem: false
    tag: latest
  name: dockerregistry
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
