apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Gotify is a simple server for sending and receiving
      messages (in real time per WebSocket)
    kubero.dev/template.icon: https://raw.githubusercontent.com/gotify/logo/master/gotify-logo.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://github.com/gotify/server/raw/master/ui.png"]'
    kubero.dev/template.source: https://github.com/gotify/server
    kubero.dev/template.tags: '["monitoring"]'
    kubero.dev/template.title: Gotify
    kubero.dev/template.website: https://gotify-net
  name: gotify
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: GOTIFY_DEFAULTUSER_NAME
    value: admin
  - name: GOTIFY_DEFAULTUSER_PASS
    value: admin
  - name: GOTIFY_SERVER_PORT
    value: '8080'
  - name: GOTIFY_REGISTRATION
    value: 'false'
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /app/data
    name: gotify-volume
    size: 1Gi
    storageClass: standard
  image:
    containerPort: '8080'
    repository: gotify/server
    tag: latest
  name: gotify
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
