apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: An easy-to-use photo-management-system to manage
      and share photos.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/37916028?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://lycheeorg.github.io/assets/3.BzY-5hAj.jpg"]'
    kubero.dev/template.source: https://github.com/LycheeOrg/Lychee
    kubero.dev/template.tags: '["Search"]'
    kubero.dev/template.title: Lychee
    kubero.dev/template.website: https://lycheeorg.github.io/
  labels:
    manager: kubero
  name: lychee
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: PHP_TZ
    value: UTC
  - name: DB_CONNECTION
    value: sqlite
  - name: APP_ENV
    value: local
  - name: DB_DATABASE
    value: /local/db/lychee
  - name: STARTUP_DELAY
    value: '5'
  - name: TRUSTED_PROXIES
    value: '*'
  - name: APP_FORCE_HTTPS
    value: 'false'
  - name: APP_URL
    value: https://lychee.localhost
  extraVolumes:
  - accessMode: ReadWriteOnce
    accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /local/db
    name: lychee-db-volume
    size: 1Gi
    storageClass: standard
  - accessMode: ReadWriteOnce
    accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /uploads
    name: lychee-upload-volume
    size: 1Gi
    storageClass: standard
  image:
    containerPort: '80'
    pullPolicy: Always
    repository: lycheeorg/lychee
    tag: latest
  name: lychee
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
