apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Ambient sounds for focus and calm.
    kubero.dev/template.icon: https://moodist.app/logo.svg
    kubero.dev/template.installation: ''
    kubero.dev/template.links: 'null'
    kubero.dev/template.screenshots: 'null'
    kubero.dev/template.source: https://github.com/remvze/moodist
    kubero.dev/template.tags: '["tools"]'
    kubero.dev/template.title: Moodist
    kubero.dev/template.website: https://moodist.app/
  labels:
    manager: kubero
  name: moodist
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes: []
  image:
    containerPort: 8080
    pullPolicy: Always
    repository: ghcr.io/remvze/moodist
    tag: latest
  name: moodist
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
