apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: The modern spam protection. Protects your forms
      from spam by simply checking the content. Open source, Free to use, Accessible,
      and Self-Hosted.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/83111146?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://d4.alternativeto.net/HPWhNJQo67junwVeSlN5ovWPz-UkZrQel0IxkNXUVbs/rs:fit:1200:1200:0/g:ce:0:0/YWJzOi8vZGlzdC9zL21vc3Bhcm9fMTA2NTE1X2Z1bGwuanBn.jpg","https://d4.alternativeto.net/DYwswFga7YcsviDw-b71168EBIS45dqsbHE0cNb8phk/rs:fit:1200:1200:0/g:ce:0:0/YWJzOi8vZGlzdC9zL21vc3Bhcm9fNTUyMjcxX2Z1bGwuanBn.jpg","https://d4.alternativeto.net/AsvhGcW3WdllXHft46cSiW5yq_l3bgdyf1-EARYjSzU/rs:fit:1200:1200:0/g:ce:0:0/YWJzOi8vZGlzdC9zL21vc3Bhcm9fMjgyMjI5X2Z1bGwuanBn.jpg","https://d4.alternativeto.net/8jPSunVUELUMLlyhW0UjOYFCQm9uKkgwE38WdUYm0V4/rs:fit:1200:1200:0/g:ce:0:0/YWJzOi8vZGlzdC9zL21vc3Bhcm9fMjYzNjQ4X2Z1bGwuanBn.jpg"]'
    kubero.dev/template.source: https://github.com/mosparo/mosparo
    kubero.dev/template.tags: '["spam protection"]'
    kubero.dev/template.title: Mosparo
    kubero.dev/template.website: https://mosparo.io/
  name: mosparo
spec:
  addons:
  - displayName: Kubero Mysql
    env: []
    icon: /img/addons/MySQL.png
    id: kubero-operator
    kind: KuberoMysql
    resourceDefinitions:
      KuberoMysql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMysql
        metadata:
          name: mosparo-mysql
        spec:
          mysql:
            auth:
              createDatabase: true
              database: mosparo
              password: mysecret
              rootPassword: mysecret
              username: mosparo
            global:
              storageClass: linode-block-storage
            primary:
              persistence:
                accessModes:
                - ReadWriteOnce
                size: 1Gi
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: APP_SECRET
    value: mySecret
  - name: MOSPARO_ENABLE_WEBSERVER
    value: '1'
  - name: MOSPARO_ENABLE_CRON
    value: '1'
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /mosparo-data
    name: mosparo-volume
    size: 1Gi
    storageClass: standard
  image:
    containerPort: '80'
    repository: mosparo/mosparo
    tag: latest
  name: mosparo
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
