apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Free and source-available fair-code licensed
      workflow automation tool. Easily automate tasks across different services.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/45487711?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://camo.githubusercontent.com/9a0a5cdb7d4805104de24a4626a015cdc4ed26062b9fb5f6beda2a8b6d5c68c2/68747470733a2f2f6e386e696f73746f726167656163636f756e742e626c6f622e636f72652e77696e646f77732e6e65742f6e386e696f2d7374726170692d626c6f62732d70726f642f6173736574732f6769746875625f73637265656e5f325f383631353532333463332e706e67","https://raw.githubusercontent.com/n8n-io/n8n/master/assets/n8n-screenshot.png"]'
    kubero.dev/template.source: https://github.com/n8n-io/n8n
    kubero.dev/template.tags: '["workflow","automation"]'
    kubero.dev/template.title: n8n
    kubero.dev/template.website: https://n8n.io
  name: n8n
spec:
  addons:
  - displayName: Kubero Postgresql
    env: []
    icon: /img/addons/postgresql.png
    id: kubero-operator
    kind: KuberoPostgresql
    resourceDefinitions:
      KuberoPostgresql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoPostgresql
        metadata:
          name: n8n-postgres
        spec:
          postgresql:
            global:
              postgresql:
                auth:
                  database: postgres
                  password: '123456'
                  postgresPassword: postgres
                  username: n8n
              storageClass: linode-block-storage
            primary:
              persistence:
                size: 1Gi
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: DB_TYPE
    value: postgresdb
  - name: DB_POSTGRESDB_HOST
    value: n8n-postgres-postgresql
  - name: DB_POSTGRESDB_PORT
    value: '5432'
  - name: DB_POSTGRESDB_USER
    value: n8n
  - name: DB_POSTGRESDB_PASSWORD
    value: '123456'
  - name: N8N_BASIC_AUTH_ACTIVE
    value: 'false'
  - name: DB_POSTGRESDB_DATABASE
    value: postgres
  extraVolumes: []
  image:
    containerPort: '5678'
    repository: docker.n8n.io/n8nio/n8n
    tag: latest
  name: n8n
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
