apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Connective Technology for Adaptive Edge & Distributed
      Systems
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/10203055?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '[]'
    kubero.dev/template.source: https://github.com/nats-io/nats-server
    kubero.dev/template.tags: '["network","pubsub","microservices"]'
    kubero.dev/template.title: Nats
    kubero.dev/template.website: https://nats.io
  name: nats
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes: []
  image:
    containerPort: '4222'
    repository: nats
    tag: latest
  name: nats
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
