apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: ntfy (pronounced "notify") is a simple HTTP-based
      pub-sub notification service. With ntfy, you can send notifications to your
      phone or desktop via scripts from any computer, without having to sign up or
      pay any fees
    kubero.dev/template.icon: https://ntfy.sh/_next/static/media/logo.077f6a13.svg
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://ntfy.sh/static/img/screenshot-web-detail.png","https://ntfy.sh/static/img/screenshot-curl.png","https://ntfy.sh/static/img/screenshot-phone-notification.jpg","https://ntfy.sh/static/img/screenshot-phone-detail.jpg"]'
    kubero.dev/template.source: https://github.com/binwiederhier/ntfy
    kubero.dev/template.tags: '["notifications","push","pubsub"]'
    kubero.dev/template.title: NTFY
    kubero.dev/template.website: https://ntfy.sh/
  name: ntfy
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /var/cache/ntfy
    name: ntfy-cache-volume
    size: 500Mi
    storageClass: standard
  image:
    command:
    - ntfy
    - serve
    containerPort: '80'
    repository: binwiederhier/ntfy
    tag: latest
  name: ntfy
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
