apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: The open source password manager for teams
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/4386228?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/passbolt/passbolt_styleguide/master/src/img/screenshots/teaser-screenshot-login.png","https://raw.githubusercontent.com/passbolt/passbolt_styleguide/master/src/img/screenshots/teaser-screenshot-share.png","https://raw.githubusercontent.com/passbolt/passbolt_styleguide/master/src/img/screenshots/teaser-screenshot4.png"]'
    kubero.dev/template.source: https://github.com/passbolt/passbolt_api
    kubero.dev/template.tags: '["password","security"]'
    kubero.dev/template.title: Passbolt
    kubero.dev/template.website: https://www.passbolt.com
  name: passbolt
spec:
  addons:
  - displayName: Kubero Mysql
    env: []
    icon: /img/addons/MySQL.png
    id: kubero-operator
    kind: KuberoMysql
    resourceDefinitions:
      KuberoMysql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMysql
        metadata:
          name: passbolt-mysql
        spec:
          mysql:
            auth:
              createDatabase: true
              database: passbolt
              password: changeme
              rootPassword: changeme
              username: passbolt
            global:
              storageClass: standard
            primary:
              persistence:
                accessModes:
                - ReadWriteOnce
                size: 1Gi
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: APP_FULL_BASE_URL
    value: http://passbolt.mydomain.com
  - name: DATASOURCES_DEFAULT_HOST
    value: passbolt-mysql
  - name: DATASOURCES_DEFAULT_USERNAME
    value: passbolt
  - name: DATASOURCES_DEFAULT_PASSWORD
    value: changeme
  - name: DATASOURCES_DEFAULT_DATABASE
    value: passbolt
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    mountPath: /etc/passbolt/gpg
    name: passbolt-gpg-volume
    size: 1Gi
  - accessModes:
    - ReadWriteOnce
    mountPath: /etc/passbolt/jwt
    name: passbolt-jwt-volume
    size: 1Gi
  image:
    containerPort: '80'
    repository: passbolt/passbolt
    tag: latest-ce
  name: passbolt
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
