apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: The simplest and most complete UI for your private
      registry
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/5429470?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: 'null'
    kubero.dev/template.source: https://github.com/Joxit/docker-registry-ui
    kubero.dev/template.tags: '["registry"]'
    kubero.dev/template.title: Docker Registry UI
    kubero.dev/template.website: https://joxit.dev/docker-registry-ui/
  name: registry-ui
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: PROC_TYPE
    value: web
  - name: PORT
    value: '8080'
  - name: SINGLE_REGISTRY
    value: 'true'
  - name: REGISTRY_TITLE
    value: Kubero
  - name: DELETE_IMAGES
    value: 'true'
  - name: SHOW_CONTENT_DIGEST
    value: 'true'
  - name: SHOW_CATALOG_NB_TAGS
    value: 'true'
  - name: TAGLIST_PAGE_SIZE
    value: '50'
  - name: CATALOG_ELEMENTS_LIMIT
    value: '500'
  - name: NGINX_LISTEN_PORT
    value: '8080'
  - name: NGINX_PROXY_PASS_URL
    value: https://regnew.demo.kubero.dev
  - name: NGINX_PROXY_HEADER_Host
    value: regnew.demo.kubero.dev
  - name: NGINX_PROXY_PASS_HEARER_Authorization
    value: Authorization
  extraVolumes: []
  image:
    containerPort: '8080'
    repository: joxit/docker-registry-ui
    run:
      securityContext:
        readOnlyRootFilesystem: false
    tag: main
  name: registry-ui
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
