apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: SQLPad is a web-based SQL editor that allows
      you to write queries, visualize data, and share your results.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/67432073?s=48&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://user-images.githubusercontent.com/303966/99915755-32f78e80-2ccb-11eb-9f74-b18846d6108d.png"]'
    kubero.dev/template.source: https://github.com/sqlpad/sqlpad
    kubero.dev/template.tags: '["tools","database"]'
    kubero.dev/template.title: SQLPad
    kubero.dev/template.website: https://getsqlpad.com/
  labels:
    manager: kubero
  name: sqlpad
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: SQLPAD_ADMIN_PASSWORD
    value: admin
  - name: SQLPAD_ADMIN
    value: admin
  extraVolumes: []
  image:
    containerPort: '3000'
    pullPolicy: Always
    repository: sqlpad/sqlpad
    run:
      command: node index.js
      readOnlyAppStorage: false
      repository: node
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      tag: latest
    tag: latest
  name: sqlpad
  serviceAccount:
    annotations: {}
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
