apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Sshwifty is a SSH and Telnet connector made for
      the Web
    kubero.dev/template.icon: https://raw.githubusercontent.com/meienberger/runtipi-appstore/master/apps/sshwifty/metadata/logo.jpg
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/nirui/sshwifty/master/Screenshot.png"]'
    kubero.dev/template.source: https://github.com/nirui/sshwifty
    kubero.dev/template.tags: '["client"]'
    kubero.dev/template.title: Sshwifty
    kubero.dev/template.website: https://sshwifty-demo.nirui.org
  name: sshwifty
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes: []
  image:
    containerPort: '8182'
    repository: niruix/sshwifty
    tag: latest
  name: sshwifty
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
