apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Umami is a simple, fast, privacy-focused alternative
      to Google Analytics.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/105618662?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://umami.is/images/languages.png"]'
    kubero.dev/template.source: https://github.com/umami-software/umami
    kubero.dev/template.tags: '["analytics"]'
    kubero.dev/template.title: umami
    kubero.dev/template.website: https://umami.is/
  name: umami
spec:
  addons:
  - displayName: Kubero Postgresql
    env: []
    icon: /img/addons/postgresql.png
    id: kubero-operator
    kind: KuberoPostgresql
    resourceDefinitions:
      KuberoPostgresql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoPostgresql
        metadata:
          name: umami-umami
        spec:
          postgresql:
            global:
              postgresql:
                auth:
                  database: umami
                  password: umami
                  postgresPassword: umamiroot
                  username: umami
              storageClass: linode-block-storage
            primary:
              persistence:
                size: 1Gi
  cronjobs: []
  deploymentstrategy: umami
  envVars:
  - name: DATABASE_URL
    value: postgresql://umami:umami@umami-umami-postgresql:5432/umami
  - name: DATABASE_TYPE
    value: postgresql
  - name: HASH_SALT
    value: replace-me-with-a-random-string
  extraVolumes: []
  image:
    containerPort: '3000'
    repository: ghcr.io/umami-software/umami
    tag: postgresql-latest
  name: umami
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
