apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Lightweight collaborative Whiteboard / Sketchboard
    kubero.dev/template.icon: https://static-00.iconduck.com/assets.00/whiteboard-icon-512x416-i0xojg3v.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/cracker0dks/whiteboard/refs/heads/master/doc/start.png"]'
    kubero.dev/template.source: https://github.com/cracker0dks/whiteboard
    kubero.dev/template.categories: '["school"]'
    kubero.dev/template.title: Whiteboard
    kubero.dev/template.website: https://github.com/cracker0dks/whiteboard
  labels:
    manager: kubero
  name: whiteboard
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes: []
  image:
    containerPort: 8080
    pullPolicy: Always
    repository: rofl256/whiteboard
    tag: latest
  name: whiteboard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
