apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: trilium
spec:
  name: trilium
  deploymentstrategy: docker
  image:
    repository: zadam/trilium
    tag: latest
    containerPort: "8080"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /home/node/trilium-data
    name: trilium-data
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
