apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: homarr
spec:
  name: homarr
  deploymentstrategy: docker
  image:
    repository: ghcr.io/ajnart/homarr
    tag: latest
    containerPort: "7575"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /app/data/configs
    name: homar-config
    size: 10Mi
    storageClass: standard
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /app/public/icons
    name: homarr-icons
    size: 200Mi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0