apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Wiki.js is a modern, lightweight and powerful
      wiki app built on Node.js, Git and Markdown.
    kubero.dev/template.icon: https://raw.githubusercontent.com/requarks/wiki/main/client/static/favicons/android-chrome-256x256.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: 'null'
    kubero.dev/template.source: https://github.com/Requarks/wiki
    kubero.dev/template.categories: '["documentation", "work", "collaboration", "utilities"]'
    kubero.dev/template.title: Wiki.js
    kubero.dev/template.website: https://js.wiki/
  name: wikijs
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: DB_TYPE
    value: sqlite
  - name: DB_FILEPATH
    value: /wiki/data/wikisj.db
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /wiki/data
    name: wikijs-data
    size: 1Gi
    storageClass: standard
  image:
    containerPort: '3000'
    repository: ghcr.io/requarks/wiki
    tag: latest
  name: wikijs
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
