apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Photoview is a simple and user-friendly photo
      gallery that is made for photographers and aims to provide an easy and fast
      way to navigate directories.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/75802894?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/photoview/photoview/master/screenshots/timeline.png"]'
    kubero.dev/template.source: https://github.com/photoview/photoview
    kubero.dev/template.categories: '["utilities"]'
    kubero.dev/template.title: Photoview
    kubero.dev/template.website: https://photoview.github.io/
  name: photoview
spec:
  addons:
  - displayName: Kubero Mysql
    env: []
    icon: /img/addons/MySQL.png
    id: kubero-operator
    kind: KuberoMysql
    resourceDefinitions:
      KuberoMysql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMysql
        metadata:
          name: photoview-mysql
        spec:
          mysql:
            auth:
              createDatabase: true
              database: photoview
              password: photoview
              rootPassword: rootpw
              username: photoview
            global:
              storageClass: default
            primary:
              persistence:
                accessModes:
                - ReadWriteOnce
                size: 1Gi
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: PROC_TYPE
    value: web
  - name: PORT
    value: '8080'
  - name: PHOTOVIEW_DATABASE_DRIVER
    value: mysql
  - name: PHOTOVIEW_MYSQL_URL
    value: photoview:photoview@tcp(photoview-mysql)/photoview
  - name: PHOTOVIEW_LISTEN_IP
    value: 0.0.0.0
  - name: PHOTOVIEW_LISTEN_PORT
    value: '8080'
  - name: PHOTOVIEW_MEDIA_CACHE
    value: /tmp
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /photoview/images
    name: photoview-images
    size: 1Gi
    storageClass: default
  image:
    containerPort: '8080'
    repository: viktorstrate/photoview
    tag: '2'
  name: photoview
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
